### ISSUE TITLE
pip installation issues if not editable (-e)

### ISSUE THREAD

**Issue by colemanjs** [ORNL-MDF/Myna#39]
# clone repository and change directory to cloned repository
git clone https://github.com/ORNL-MDF/Myna
cd **M**yna

**Comment by streeve** [comment]
Thank you for your interest in Myna! Are you willing to put in a pull request for this new feature? Please see the contribution guide: https://github.com/ORNL-MDF/Myna/blob/main/CONTRIBUTING.md

**Comment by gknapp1** [comment]
I was able to reproduce this after creating a clean virtual environment, cloning, installing myna and attempting to import. When you run `import myna` from outside the root folder, Python is not able to find the "myna" module. 

I believe that the current build CI doesn't catch this because `pytest` is being run from within the root folder of the cloned repo.

There is probably a way around this without renaming the repository, but still looking into that.

**Comment by gknapp1** [comment]
So, this errors comes from a combination of elements that weren't caught in our development environments:

1. When installing a Python package with `pip install -e .`, the source directory is symbolically linked to the `site-packages` directory so it shows up on the path when importing.
2. The directory you run the Python command from is also in your working path, so imports will work if you are in the root directory of the repository.

I believe that the issue is an improper specification in the `pyproject.toml` file, so I will look into what needs to be changed there.

**Comment by gknapp1** [comment]
Upon further investigation, my understanding is that to fully resolve this issue we either need to:

1. Reorganize the repository to be compatible with either the src-layout or flat-layout style described in [the setuptools docs](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html), or
2. Switch to a different build system, like [poetry](https://python-poetry.org/), to better handle our unconventional directory layout.

I'm more inclined towards option 1 to avoid requiring installing additional build systems, though that may take a little bit of time to implement than option 2. In the meantime, @colemanjs please use `pip install -e .` to install Myna. That should make everything behave as intended.

**Comment by gknapp1** [comment]
Alternatively, you can use the following to clone the source code and install `myna` in a single command. This will clone the main branch to your current working directory:

 `pip install --src . -e git+https://github.com/ORNL-MDF/Myna#egg=myna`

**Comment by streeve** [comment]
I picked a bad issue to be sarcastic on, I didn't think this would actually break anything. We can use either: 
```
git clone https://github.com/ORNL-MDF/myna
git clone https://github.com/ORNL-MDF/Myna myna
```

but I can also rename the repo (which "shouldn't" break anything)
